sonar.projectKey=nyamatullahmohammed_devsecops_training
sonar.organization=nyamatullahmohammed
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.python.coverage.reportPaths=coverage.xml
sonar.login=${SONAR_TOKEN}